# Generated by Django 3.1.6 on 2021-07-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
