# Generated by Django 3.1.6 on 2021-07-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210705_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tel',
            new_name='phone',
        ),
    ]
