# Generated by Django 3.1.6 on 2021-07-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210710_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='p_author',
            field=models.CharField(max_length=200),
        ),
    ]
