# Generated by Django 3.1.6 on 2021-07-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='background.jpg', upload_to='cover_img'),
        ),
    ]
