# Generated by Django 3.1.6 on 2021-08-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count_sold',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='count download'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_abstract',
            field=models.TextField(max_length=2000),
        ),
    ]
