# Generated by Django 3.2.5 on 2021-07-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
